# Generated by Django 2.2.4 on 2019-08-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='shoikh123', max_length=256)),
                ('name', models.CharField(default='Shaik', max_length=256)),
            ],
        ),
    ]
