# Generated by Django 2.2.4 on 2019-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(default='Guest', max_length=150, verbose_name='username'),
        ),
    ]
