# Generated by Django 2.2.4 on 2019-08-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190815_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.Lobby'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.Player'),
        ),
    ]
