# Generated by Django 2.2.4 on 2019-08-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190810_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
