# Generated by Django 2.2.4 on 2019-08-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='shoikh123', max_length=256)),
                ('name', models.CharField(default='Shaik', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('state', models.IntegerField(choices=[('WAITING', 0), ('RUNNING', 1), ('FINISHED', 2)], default='WAITING')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lobby_admin', to='api.Player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Game')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lobby_players', to='api.Player')),
            ],
        ),
    ]
