# Generated by Django 2.2.4 on 2019-08-10 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_lobby_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='lobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='api.Lobby'),
            preserve_default=False,
        ),
    ]
