# Generated by Django 2.2.4 on 2019-08-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190810_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='url',
        ),
    ]
